server:
  port: 50001
  servlet:
    context-path: /rest/v1
    session:
      cookie:
        name: SAMPLESESSION

spring:
  flyway:
    table: FLYWAY_SCHEMA_HISTORY
  jackson:
    default-property-inclusion: non_null
  jpa:
    open-in-view: false
  main:
    banner-mode: off
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true
